---
abstract: 'Declare extension for Params::Dry - Simple Global Params Management System which helps you to keep the DRY rule everywhere'
author:
  - 'Pawel Guspiel (neo77) <neo@cpan.org>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Params-Dry-Declare
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  Params::Dry: 0
  perl: 5.006
provides:
    Params::Dry:
        file: lib/Params/Dry/Declare.pm
        version: 0.9905
resources: 
    license: http://opensource.org/licenses/artistic-license-2.0.php
    repository: https://github.com/neo77/Params-Dry-Declare
distribution_type: module
keywords:
    - params
    - parameters
    - 'named parameters'
version: 0.9905
